"""udev rules that give plugins access to exactly the hardware they declared and the user approved.

Plugins run without root. A device node is only readable by the group 'lifaco-usb' (USB/hidraw) or 'lifaco-i2c'
(SMBus), and a plugin process only joins those groups if it declared the permission.
"""

import logging
import os
import shutil
import subprocess

log = logging.getLogger("fancontrol-linuxd")
RULES_FILE = "/etc/udev/rules.d/70-lifaco-plugins.rules"
HEADER = "# Generated by LiFaCo from the approved permissions of enabled lighting plugins. Do not edit.\n"


def render_rules(approved):
    """approved: list of (plugin id, permissions). Returns the rules file content."""
    lines = [HEADER]
    i2c = False
    for pid, perms in sorted(approved, key=lambda p: p[0]):
        for usb in perms["usb"]:
            vid, pid_ = usb.split(":")
            lines.append(f'# {pid}\n'
                         f'SUBSYSTEM=="hidraw", ATTRS{{idVendor}}=="{vid}", ATTRS{{idProduct}}=="{pid_}", '
                         f'GROUP="lifaco-usb", MODE="0660"\n'
                         f'SUBSYSTEM=="usb", ENV{{DEVTYPE}}=="usb_device", ATTR{{idVendor}}=="{vid}", '
                         f'ATTR{{idProduct}}=="{pid_}", GROUP="lifaco-usb", MODE="0660"\n')
        i2c = i2c or perms["i2c"]
    if i2c:
        lines.append('# SMBus access (approved by the user for at least one plugin)\n'
                     'SUBSYSTEM=="i2c-dev", GROUP="lifaco-i2c", MODE="0660"\n')
    return "".join(lines)


def sync(approved, path=RULES_FILE):
    """Write the rules if they changed and tell udev. Does nothing when not running as root."""
    if os.geteuid() != 0:
        return False
    content = render_rules(approved)
    try:
        with open(path) as f:
            if f.read() == content:
                return False
    except FileNotFoundError:
        if content == HEADER:
            return False
    except OSError:
        pass
    try:
        with open(path, "w") as f:
            f.write(content)
    except OSError as e:
        log.warning("Cannot write udev rules: %s", e)
        return False
    if any(p["i2c"] for _pid, p in approved) and shutil.which("modprobe"):
        subprocess.run(["modprobe", "i2c-dev"], capture_output=True, timeout=20, check=False)
    if shutil.which("udevadm"):
        try:
            subprocess.run(["udevadm", "control", "--reload-rules"], capture_output=True, timeout=20, check=False)
            subprocess.run(["udevadm", "trigger", "--subsystem-match=hidraw", "--subsystem-match=usb",
                            "--subsystem-match=i2c-dev", "--action=add"], capture_output=True, timeout=30, check=False)
        except (OSError, subprocess.SubprocessError) as e:
            log.warning("udev could not be reloaded: %s", e)
    return True
